### ISSUE TITLE
Error on running the run-test.sh script 

### ISSUE THREAD

**Issue by algone** [pomadchin/geo-env#15]
So I updated my local repo and checked that am on master. Then I ran the install.sh script, which build successfully. However, invoking the test script brings up the following message:

> Error: Could not find or load main class com.example.geomesa.accumulo.AccumuloQuickStart

That is weird !

**Comment by algone** [comment]
And neither is the update.sh running...
`./update.sh
error: unknown switch`D'
usage: git fetch [<options>] [<repository> [<refspec>...]]
   or: git fetch [<options>] <group>
   or: git fetch --multiple [<options>] [(<repository> | <group>)...]
   or: git fetch --all [<options>]
`

**Comment by pomadchin** [comment]
Can you provide more information about `not find class err`? (we are pulling [this](https://github.com/geomesa/geomesa-tutorials/blob/e8d9eabba5aa277282e0feb6749c8e9e62296b8a/geomesa-quickstart-accumulo/pom.xml#L17) tutorial commit) 
Good catch with an update script, thanks!

**Comment by algone** [comment]
And now the result for trying to install geotrellis are in:

> [info]    [SUCCESSFUL ] org.apache.hadoop#hadoop-yarn-server-nodemanager;2.7.1!hadoop-yarn-server-nodemanager.jar (1060ms)
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]  ::          UNRESOLVED DEPENDENCIES         ::
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]  :: com.azavea.geotrellis#geotrellis-services_2.10;0.10.0-SNAPSHOT: not found
> [warn]  :: com.azavea.geotrellis#geotrellis-util_2.10;0.10.0-SNAPSHOT: not found
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn] 
> [warn]  Note: Unresolved dependencies path:
> [warn]      com.azavea.geotrellis:geotrellis-services_2.10:0.10.0-SNAPSHOT (/data/geotrellis-chatta-demo/geotrellis/build.sbt#L24-33)
> [warn]        +- com.azavea:geotrellis-tutorial-project_2.10:0.1-SNAPSHOT
> [warn]      com.azavea.geotrellis:geotrellis-util_2.10:0.10.0-SNAPSHOT
> [warn]        +- com.azavea.geotrellis:geotrellis-vector_2.10:0.10.0-SNAPSHOT
> [warn]        +- com.azavea.geotrellis:geotrellis-raster_2.10:0.10.0-SNAPSHOT
> [warn]        +- com.azavea.geotrellis:geotrellis-spark_2.10:0.10.0-SNAPSHOT (/data/geotrellis-chatta-demo/geotrellis/build.sbt#L24-33)
> [warn]        +- com.azavea.geotrellis:geotrellis-spark-etl_2.10:0.10.0-SNAPSHOT (/data/geotrellis-chatta-demo/geotrellis/build.sbt#L24-33)
> [warn]        +- com.azavea:geotrellis-tutorial-project_2.10:0.1-SNAPSHOT
> sbt.ResolveException: unresolved dependency: com.azavea.geotrellis#geotrellis-services_2.10;0.10.0-SNAPSHOT: not found
> unresolved dependency: com.azavea.geotrellis#geotrellis-util_2.10;0.10.0-SNAPSHOT: not found
>     at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:294)
>     at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
>     at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
>     at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
>     at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:155)
>     at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:132)
>     at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
>     at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
>     at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
>     at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
>     at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
>     at xsbt.boot.Using$.withResource(Using.scala:10)
>     at xsbt.boot.Using$.apply(Using.scala:9)
>     at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
>     at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
>     at xsbt.boot.Locks$.apply0(Locks.scala:31)
>     at xsbt.boot.Locks$.apply(Locks.scala:28)
>     at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
>     at sbt.IvySbt.withIvy(Ivy.scala:127)
>     at sbt.IvySbt.withIvy(Ivy.scala:124)
>     at sbt.IvySbt$Module.withModule(Ivy.scala:155)
>     at sbt.IvyActions$.updateEither(IvyActions.scala:168)
>     at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1392)
>     at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1388)
>     at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1422)
>     at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1420)
>     at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
>     at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1425)
>     at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1419)
>     at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
>     at sbt.Classpaths$.cachedUpdate(Defaults.scala:1442)
>     at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1371)
>     at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1325)
>     at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
>     at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
>     at sbt.std.Transform$$anon$4.work(System.scala:63)
>     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
>     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
>     at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
>     at sbt.Execute.work(Execute.scala:235)
>     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
>     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
>     at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
>     at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)
> [error](*:update) sbt.ResolveException: unresolved dependency: com.azavea.geotrellis#geotrellis-services_2.10;0.10.0-SNAPSHOT: not found
> [error] unresolved dependency: com.azavea.geotrellis#geotrellis-util_2.10;0.10.0-SNAPSHOT: not found
> [error] Total time: 89 s, completed Feb 29, 2016 11:51:57 PM
> FATA[0000] Error: Path not specified  
> FATA[0000] Error: Path not specified

something is not right...

**Comment by algone** [comment]
regarding the class not found, I tried it again, and same thing....

> gone@gonespatial ~/geodocker/geodocker-cluster/install/geomesa $ ./run-test.shError: Could not find or load main class com.example.geomesa.accumulo.AccumuloQuickStart

The is no so much info,  it bails out almost immediately

**Comment by algone** [comment]
It sees that some of the dependencies for the 2.10.5 are missing. I Could not build the Chatta demo, always complaining about the com.azavea.geotrellis#geotrellis-services_2.10;0.10.0-SNAPSHOT. Do you have a build that is actually working?

**Comment by pomadchin** [comment]
@algone sry for that, actually chatta demo is a not up to geotrellis master branch, we had multiple of changes which had to be reflected in the demo project; will try to fix it today

**Comment by algone** [comment]
@pomadchin That would great, am itching to get this Geotrellis thing working. BTW I tried different scala versions (2.10, 2.10.5, 2.11.5, 2.11.7) but nothing worked. I have now managed to install geomesa, and partly geotrellis(apart from the chatta demo - ) if that works I will move on to Geowave

**Comment by pomadchin** [comment]
#20

**Comment by pomadchin** [comment]
Everything was fixed and updated; you may reopen / open a new issue if you would have some problems.
