### ISSUE TITLE
Error on running the run-test.sh script for geomesa

### ISSUE THREAD

**Issue by algone** [pomadchin/geo-env#16]
So I updated my local repo and checked that am on master. Then I ran the install.sh script, which build successfully. However, invoking the test script brings up the following message:

> Error: Could not find or load main class com.example.geomesa.accumulo.AccumuloQuickStart

That is weird !

**Comment by algone** [comment]
Finally was able to run the test script

**Comment by pomadchin** [comment]
@algone Sry, and what was wrong actually?

**Comment by algone** [comment]
@pomadchin The dependencies were actually not resolving. This time too, it first failed, then I repeated the execution of the script again and then it worked.
