### ISSUE TITLE
Geowave builds but....run-test.sh  cannot find tablet servers

### ISSUE THREAD

**Issue by algone** [pomadchin/geo-env#17]
Looks like again something is not right with my nodes:

> ./run-test.sh
> --2016-02-29 23:52:07--  http://naciscdn.org/naturalearth/50m/cultural/ne_50m_admin_0_countries.zip
> Resolving naciscdn.org (naciscdn.org)... 146.201.97.163
> Connecting to naciscdn.org (naciscdn.org)|146.201.97.163|:80... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 817686 (799K) [application/x-zip-compressed]
> Saving to: 'ne_50m_admin_0_countries.zip'

100%[============================================================================================================================================================>] 817,686     1.26KB/s   in 8.8s   

2016-02-29 23:52:16 (90.3 KB/s) - 'ne_50m_admin_0_countries.zip' saved [817686/817686]

Archive:  ne_50m_admin_0_countries.zip
  inflating: ne_50m_admin_0_countries.README.html  
 extracting: ne_50m_admin_0_countries.VERSION.txt  
  inflating: ne_50m_admin_0_countries.dbf  
  inflating: ne_50m_admin_0_countries.prj  
  inflating: ne_50m_admin_0_countries.shp  
  inflating: ne_50m_admin_0_countries.shx  
29 Feb 23:52:18 WARN [client.ClientConfiguration] - Found no client.conf in default paths. Using default client configuration values.
29 Feb 23:52:22 WARN [impl.ServerClient] - There are no tablet servers: check that zookeeper and accumulo are running.

**Comment by pomadchin** [comment]
Probably a memory issue: #18

**Comment by pomadchin** [comment]
@algone can you check new images versions?

**Comment by pomadchin** [comment]
@algone closed now, you can re-open it if that happen again, and check out that you have enough ram.
