### ISSUE TITLE
Fix demo projects to a stable API version

### ISSUE THREAD

**Issue by pomadchin** [pomadchin/geo-env#20]
GeoMesa tutorial and GeoTrellis tutorials are out of date; we have to update it and to fix on stable versions to be available for install and run.

**Comment by krlng** [comment]
I fixed it by removing the SNAPSHOT from the version, so that it is only `1.2.0`

**Comment by krlng** [comment]
Or remove the checkout in the install script to use the latest version

**Comment by pomadchin** [comment]
@nik-ffm https://github.com/geomesa/geomesa-tutorials/blob/master/pom.xml#L16

**Comment by pomadchin** [comment]
Current status: 
- [x] GeoTrellis 10-RC-4
- [x] GeoMesa 1.2.1
- [x] GeoWave 0.9.0

**Comment by pomadchin** [comment]
we have no demo projects right now, we work on new demos.
