### ISSUE TITLE
Encoding issue while building geotrellis

### ISSUE THREAD

**Issue by algone** [pomadchin/geo-env#22]
I encountered this issue while running the geotrellis install.sh script. Here is the output log:

``[info] Compiling 2 Scala sources to /data/geotrellis/util/target/scala-2.10/classes...
[error] /data/geotrellis/proj4/src/main/java/org/osgeo/proj4j/util/PolarCoordinate.java:18:  error: unmappable character for encoding ASCII
[error]         return String.format("<??%f, ??%f>", lam, phi);
[error]                                ^
[error] /data/geotrellis/proj4/src/main/java/org/osgeo/proj4j/util/PolarCoordinate.java:18:  error: unmappable character for encoding ASCII
[error]         return String.format("<??%f, ??%f>", lam, phi);
[error]                                 ^
[error] /data/geotrellis/proj4/src/main/java/org/osgeo/proj4j/util/PolarCoordinate.java:18:  error: unmappable character for encoding ASCII
[error]         return String.format("<??%f, ??%f>", lam, phi);
[error]                                      ^
[error] /data/geotrellis/proj4/src/main/java/org/osgeo/proj4j/util/PolarCoordinate.java:18:  error: unmappable character for encoding ASCII
[error]         return String.format("<??%f, ??%f>", lam, phi);
[error]                                       ^
[error](proj4/compile:compileIncremental) javac returned nonzero exit code
[error] Total time: 36 s, completed Mar 22, 2016 10:55:55 AM

**Comment by pomadchin** [comment]
Probably that was caused by a not stable GeoTrellis master branch, reopen this issue if you still have these errors, and provide more information about how you start environment. NOTE: be sure that you pulled down newest docker images from the docker hub.

**Comment by pomadchin** [comment]
Fixed by https://github.com/geotrellis/geodocker-cluster/commit/8dbfe4e148e95b4270e403da1b5a773e62a20856
