### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by pljplj** [pomadchin/geo-env#24]
I am working behind a firewall so I had to figure out how to use a proxy with docker and then it complained about certificates so I had to put my certs where docker was happy.

Now when I try to follow the directions I get the following error:

$ cd serf
$ sudo ./build.sh
[sudo] password for user:
Sending build context to Docker daemon  21.5 kB
Step 0 : FROM ubuntu:14.04
---> ab035c88d533
Step 1 : MAINTAINER Grigory Pomadchin, daunnc@gmail.com
---> Using cache
---> b3c5256d7866
Step 2 : RUN apt-get update
---> Using cache
---> 03f46a6ef4a9
Step 3 : RUN apt-get install -y dnsmasq unzip curl
---> Running in fad9d01871a0
Reading package lists...
Building dependency tree...
Reading state information...
Package dnsmasq is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  dnsmasq-base

E: Package 'dnsmasq' has no installation candidate
The command '/bin/sh -c apt-get install -y dnsmasq unzip curl' returned a non-zero code: 100

**Comment by pomadchin** [comment]
For some reason I can't reproduce this error, however it is not necessary to build this image: you can pull it from repository.

Probably, you can provide more information about the way you are trying to build this image.

**Comment by pomadchin** [comment]
@pljplj Repoen it if you still have problems.
