### ISSUE TITLE
CentOS as a default OS for images

### ISSUE THREAD

**Issue by pomadchin** [pomadchin/geo-env#36]
Currently Ubuntu is a base OS for all containers, we can try CentOS, what do you think about it, @moradology ?

**Comment by moradology** [comment]
I built a CentOS image with java/maven just to get a feel for the OS - we might even be able to just switch base images?

**Comment by pomadchin** [comment]
Yes, just to switch base images, that would be awesome. Think, that for `dev` images that's not necessary

**Comment by pomadchin** [comment]
Resolved by #45
