### ISSUE TITLE
JODA time included with spark 1.5.2 is in conflict with the AWS API and JVM versions

### ISSUE THREAD

**Issue by mchendricks1** [pomadchin/geo-env#38]
I was running geodocker-cluster and ran into an AWS error code when running the geotrellis-spark-etl built-in (e.g., SinglebandIngest) examples.

AmazonS3Exception: AWS authentication requires a valid Date or x-amz-date header

The workaround I used is documented in the following article explaining the problem.

http://theckang.com/2016/dependency-management-with-spark/

**Comment by pomadchin** [comment]
Thanks a lot, great catch, would mention this issue in a related pr!

**Comment by pomadchin** [comment]
Resolved by #45
